services:
  postgres:
    image: postgres:16-alpine
    container_name: eventsync-db
    restart: unless-stopped
    ports:
      - '5440:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventsync_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
